### PR TITLE
Redo the CSS to make things more GB-like

### PR DESCRIPTION
**Pull request by c-Vui**
I've redesigned the CSS to improve (in my opinion) the look of the website, making it more Game Boy-like, using colors similar to the DMG shell. The tables should be more readable as well, especially the headers. I've included a screenshot below of the overall design. I should note that the "expand all" cuts off with the original CSS too, and only on certain pages.

css-redesign

### CODE REVIEW

**Comment by ISSOtm** [comment]
Hi!

Whoa, I have to say, this looks really good!

However, I'm actually planning to redo gb-asm-tutorial from scratch in the coming month or so, both fixing content and hopefully improving the layout. Would you be interested in helping with that? It's fine if not, this is a very good and very much welcome improvement already ^^

**Comment by cvui** [comment]
Hiya,

Sure thing. Are you planning to use pure HTML+CSS like you have here, or do you plan to migrate it to something like Jekyll? I'd be willing to help either way, I just want to know what I'm in for.

**Comment by ISSOtm** [comment]
I'm planning to use Jekyll for convenience, yeah. Though nothing is set in stone, if you have a better idea, I'm open to suggestions.

I don't have anything in mind for the new design, but I really like the color scheme you designed!

**Comment by cvui** [comment]
I do think something like Jekyll would be appropriate for this type of tutorial, considering it's both capable of "pretty" pages relatively easily and its ease of use- this is also a static page rather than a dynamic one, so it's a good fit there, too. 

I do think re-implementing the sidebar in any way- especially by moving to Jekyll- would be helpful since it's kind of wonky and inconsistent at times- for example, on certain pages (particularly the one about jumping) the "Expand/Collapse All" button spans two lines, at least in Firefox. Even without my CSS it does that. Additionally, collapse buttons for individual buttons don't seem to work when the "Expand All" toggle is active. I hadn't really played with that, though.

The rest of this is probably dreaming: 

I think it would be cool to compile the example programs and have an embedded player run them, it would be particularly useful in a tutorial if there was breakpoints and watch points for relevant memory addresses or registers alongside it, though it would probably take a while to do that since nothing quite like that exists.

**Comment by ISSOtm** [comment]
> I do think re-implementing the sidebar in any way- especially by moving to Jekyll- would be helpful since it's kind of wonky and inconsistent at times- for example, on certain pages (particularly the one about jumping) the "Expand/Collapse All" button spans two lines, at least in Firefox. Even without my CSS it does that. Additionally, collapse buttons for individual sections don't seem to work when the "Expand All" toggle is active. I hadn't really played with that, though.

I'm fine with that, it was merely *some* way of implementing navigation. If you have a better idea, I'll take it!

> I think it would be cool to compile the example programs and have an embedded player run them, it would be particularly useful in a tutorial if there were breakpoints and watch points for relevant memory addresses or registers alongside it, though it would probably take a while to do that since nothing quite like that exists.

That would be doable, though imo better suited for a "second pass": it's worth getting the main content, and then enhancing accessibility/usability.

**Comment by cvui** [comment]
Yup, that's why I said it was "dreaming." Not strictly necessary, but it would be really cool to have. The tutorial's main content is better to have done first, and _then_ it can be enhanced.

**Comment by cyberic99** [comment]
> since nothing quite like that exists.

I think https://github.com/osnr/livegb is close to that already

**Comment by ISSOtm** [comment]
And there is https://daid.github.io/rgbds-live/. I'm a bit more concerned about the code size and integration, and this is why I'd prefer taking it into consideration later, to avoid diverting attention ^^

**Comment by cvui** [comment]
> I think https://github.com/osnr/livegb is close to that already

> And there is https://daid.github.io/rgbds-live/. 
Good finds, if we go that route! I wasn't aware these existed, but it's good to know about them.

**Comment by ISSOtm** [comment]
There's no reason not to merge this as-is; until the rewrite + redesign can be carried out, it's still better to improve the experience for readers.

**Comment by ISSOtm** [comment]
Thanks again! ^^

**Pull request merged**
