### PR TITLE
Update tiles.md

### PR DESCRIPTION
**Pull request by ApianbelleDev**
saying "how exactly are those graphics?" is grammatically wrong. it should be "what exactly are those graphics?"

### CODE REVIEW

**Comment by ApianbelleDev** [comment]
I'll let you know if I find anything else

**Comment by eievui5** [comment]
I feel like this is supposed to say “but what makes data ‘graphics’”, not “what are those graphics”

**Comment by ApianbelleDev** [comment]
> I feel like this is supposed to say “but what makes data ‘graphics’”, not “what are those graphics”

that makes more sense. I'll make those changes and submit it again.

**Comment by ApianbelleDev** [comment]
done. I tried to make it sound similar to what it was going for in the first place.

**Review by ISSOtm — APPROVED** [review]

**Pull request merged**
