### PR TITLE
Improve instruction/directive wording

### PR DESCRIPTION
**Pull request by ApianbelleDev**
the statement `Each line can contain a directive, which instructs RGBASM to do something, or an instruction` 
didn't make much sense gramatically, so I changed it to `which instructs RGBASM to do something, called an instruction` instead. that should get the idea across.

### CODE REVIEW

**Comment by eievui5** [comment]
You've changed the meaning of the sentence...

This: `Each line can contain a directive, which instructs RGBASM to do something`

and this: `or an instruction`

are separate.

**Comment by ApianbelleDev** [comment]
The way ISSO wrote still doesn't make much sense, so what is your suggestion?

**Comment by ISSOtm** [comment]
Here's mine:
```markdown
Each line can contain one of two things:
- a *directive*, which instructs RGBASM to do something, or
- an *instruction*[^instr_directive], which is written directly into the ROM.
```

**Comment by ApianbelleDev** [comment]
Okay, that looks a _lot_ better. Much more understandable.

**Comment by eievui5** [comment]
Yeah this is better.

**Review by avivace — APPROVED** [review]

**Pull request merged**
